services:
  pg-1:
    image: postgres
    container_name: "pg-1"
    ports:
      - "5433:5432"
    environment:
       POSTGRES_USER: user
       POSTGRES_PASSWORD: test
       POSTGRES_DB: postgres
    volumes:
      - pg1_data:/var/lib/postgresql/data
  pg-2:
    image: postgres
    container_name: "pg-2"
    ports:
      - "5434:5432"
    environment:
       POSTGRES_USER: user
       POSTGRES_PASSWORD: test
       POSTGRES_DB: postgres
    volumes:
      - pg2_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: "redis"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  pg1_data:
  pg2_data:
  redis_data: