spring:
  application:
    name: product_service
  datasource:
    url: "jdbc:postgresql://localhost:5433/postgres"
    username: user
    password: test
  jpa:
    showSql: true
    hibernate:
      ddlAuto: update
  data:
    redis:
      host: localhost
      port: 6379
    cache:
      type: redis
server:
  port: 8083

eureka:
    client:
        service-url:
            defaultZone: "http://localhost:8888/eureka/"
        register-with-eureka: true
        fetch-registry: true